### ISSUE TITLE
A breeder can log in or sign up to access their breeder portal. 

### ISSUE THREAD

**Issue by kagranger** [kagranger/petpeople#1]
**Task list**
- [x] Create a wireframe.
- [x] Set up atom, linters, dependancies, devdependencies, and folder structure. 
- [x] Document the data model.
- [x] Document the data flow. 
- [x] Created a User mongoose model to store user information.
- [x] Create a post route to receive user sign-up information.
- [x] Register post route with express app.
- [x] Test the server with HTTPie.
- [x] Verify user info is stored in database with mongo command.
- [x] Document the component hierarchy.
- [x] Add basic react components, index.html, and css. 
- [x] Create and style login form UI.
- [x] Add submit event listener to signup form and extract data from form. 
- [x] Send http request to server with user signup data.
- [x] Test that user signup data is stored in database. 
- [x] Add submit event listener to login form and extract data from form. 
- [x] Send http request to server with user login data.
- [x] Test that user login data is stored in database. 
- [x] Amend commits to include issue number.

**Component Hierarchy**
```javascript
<App>
    <RegistrationForm>
        <Signup />
        <Login />
    </RegistrationForm>
</App>
```

**Data Model**
```javascript
{
    listings : [
        {
            breeder-breed: "",
            image: "",
            address: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                website: ""
             }
        },
        {
            breeder-breed: "",
            image: "",
            address: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                website: ""
             }
        },
        ...
    ]
}
```

**Wireframe**
![screen shot 2018-04-27 at 10 26 51 am](https://user-images.githubusercontent.com/36418379/39376190-9fd114e6-4a05-11e8-9c46-118a97b0288d.png)

![screen shot 2018-04-27 at 10 00 39 am](https://user-images.githubusercontent.com/36418379/39376195-a7f8b962-4a05-11e8-9df8-ec84432fc059.png)
