### ISSUE TITLE
A breeder can create a listing.

### ISSUE THREAD

**Issue by kagranger** [kagranger/petpeople#2]
**Task list**
- [x] Document the component hierarchy.
- [x] Create a mongoose model to store breeder listing information.
- [x] Create a post route to receive breeder listing information.
- [x] Register post route with express app.
- [x] Verify breeder info is stored in database with mongo command.
- [x] Create a wireframe.
- [x] Add basic react components and css.
- [x] Style posting UI.
- [x] Add submit event listener to listing form and extract data from form.
- [x] Send http request to server with breeder post data.
- [x] Ensure createlisting post route checks for valid json web token.
- [x] Test that breeder post data is stored in database.
- [x] Use multer on server side to upload an image. 
- [x] Update breeder schema and router post request model to include image detail. 
- [x] Add file input to CreateListing component and style.
- [x] Adjust handlePostSubmit function to account for image upload. 

**Component Hierarchy**
```javascript
<App>
    <CreateListing />
</App>
```
**Data Flow**
![screen shot 2018-05-02 at 9 43 52 am](https://user-images.githubusercontent.com/36418379/39537104-69d2de56-4ded-11e8-8c9d-67703641d020.png)

**Data Model**
```javascript
{
    listings : [
        {
            breeder-breed: "",
            image: "",
            address: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                website: ""
             }
        },
        {
            breeder-breed: "",
            image: "",
            address: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                website: ""
             }
        },
        ...
    ]
}
```

**Wireframe**
![screen shot 2018-05-01 at 3 45 32 pm](https://user-images.githubusercontent.com/36418379/39497142-c5dae50a-4d56-11e8-9f2a-64f60505e158.png)
![screen shot 2018-05-01 at 3 37 30 pm](https://user-images.githubusercontent.com/36418379/39497145-c8fe3ce6-4d56-11e8-84f9-26b11466783a.png)
