### ISSUE TITLE
A breeder can view their listing card.

### ISSUE THREAD

**Issue by kagranger** [kagranger/petpeople#3]
**Task list**
- [x] Create a wireframe.
- [x] Document the component hierarchy.
- [x] Document the data flow.
- [x] Create a get route to retrieve breeder listing information.
- [x] Add basic react components and css.
- [x] Send http request to server to retrieve listing data.
- [x] Style listing card.
- [x] Add state for breeder and view in main App.
- [x] Create function that keeps user logged in to breeder portal if token detected in local storage.
- [x] Create log out function that sends user back to landing page and removes token, id, and email on click.
- [x] Add event listener to log out button.
- [x] Add middleware function to user route that creates and responds with a token when user signs up.
- [x] In main app sign up function store token and email in user's local storage upon sign up.
- [x] Add state within main app sign up function so user is redirected to breeder portal upon sign up. 
- [x] Create landing page for app with logo and background.
- [x] Add login/signup button to landing page.
- [x] Add event listener to login/signup button that brings up registration form modal on click.
- [x] Add search bar to landing page. 

**Component Hierarchy**
```javascript
<App>
    <CreateListing>
        <ViewListing />
    </CreateListing>
</App>
```

**Data Flow**

![screen shot 2018-05-02 at 9 55 19 am](https://user-images.githubusercontent.com/36418379/39537717-3eda6de8-4def-11e8-8aa5-5d86725fa355.png)

**Data Model**
```javascript
{
    listings : [
        {
            type: "",
            breed: "",
            cityState: "",
            availability: "",
            additional-info: "",
            name: "",
            phone: "",
            email: "",
            website: "",
            image: "",
        },
        {
            type: "",
            breed: "",
            cityState: "",
            availability: "",
            additional-info: "",
            name: "",
            phone: "",
            email: "",
            website: "",
            image: "",
        },
        ...
    ]
}
```

**Wireframe**
![screen shot 2018-05-07 at 3 33 19 pm](https://user-images.githubusercontent.com/36418379/39728501-32810d88-520c-11e8-81dd-ac35cc7148cb.png)
![screen shot 2018-05-12 at 2 06 06 pm](https://user-images.githubusercontent.com/36418379/39961616-fae1d3da-55ee-11e8-81ed-b24db2d7cc99.png)
![screen shot 2018-05-07 at 3 33 06 pm](https://user-images.githubusercontent.com/36418379/39728504-36ccfea6-520c-11e8-9eaf-5b04a1914a34.png)
![screen shot 2018-05-12 at 2 06 26 pm](https://user-images.githubusercontent.com/36418379/39961618-02dbfb4c-55ef-11e8-9e78-9e217f173f8b.png)
![screen shot 2018-05-07 at 3 12 15 pm](https://user-images.githubusercontent.com/36418379/39728506-38950c74-520c-11e8-8497-f12811490840.png)
![screen shot 2018-05-11 at 9 28 39 am](https://user-images.githubusercontent.com/36418379/39935558-4883496c-54fe-11e8-9891-4745ce8f2f48.png)
