### ISSUE TITLE
User experience enhancements.

### ISSUE THREAD

**Issue by kagranger** [kagranger/petpeople#4]
**Task list**
- [x] Refactor Signup component to utilize state instead of FormData.
- [x] Refactor Login component to utilize state instead of FormData.
- [x] Update RegistrationForm component to account for Login/Signup changes.
- [x] Update App component to reflect changes in state.
- [x] Refactor CreateListing component to utilize state and only FormData for postImage.
