### ISSUE TITLE
A breeder can delete their listing.

### ISSUE THREAD

**Issue by kagranger** [kagranger/petpeople#5]
**Task list**
- [x] Document the component hierarchy.
- [x] Create a delete route to delete breeder listing info.
- [x] Verify breeder listing info is being deleted in database using mongo command.
- [x] Update wireframe.
- [x] Add basic react component.
- [x] Create and style 'delete' button.
- [x] Add submit event listener to 'delete' button.
- [x] Send http request to server to clear breeder listing info.
- [x] Test that breeder listing info is deleted in database. 

**Component Hierarchy**
```javascript
<App>
    <CreateListing>
        <ViewListing>
            <DeleteListing />  
        </ViewListing>
    </CreateListing>
</App>
```
**Data Flow**

<img width="341" alt="screen shot 2018-05-24 at 3 27 55 pm" src="https://user-images.githubusercontent.com/36418379/40516774-15855956-5f67-11e8-8748-af6e0a746e63.png">

**Data Model**
```javascript
{
    listings : [
        {
            type: "",
            breed: "",
            image: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                city-state: "",
                website: ""
             }
        },
        {
            type: "",
            breed: "",
            image: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                city-state: "",
                website: ""
             }
        },
        ...
    ]
}
```

**Wireframe**

<img width="720" alt="screen shot 2018-05-24 at 3 26 16 pm" src="https://user-images.githubusercontent.com/36418379/40516738-dd8343d8-5f66-11e8-971d-d011322756d5.png">

<img width="1575" alt="screen shot 2018-05-24 at 3 31 51 pm" src="https://user-images.githubusercontent.com/36418379/40516900-a578a25c-5f67-11e8-8242-e211d3c7892b.png">
