### ISSUE TITLE
A breeder can create multiple listings.

### ISSUE THREAD

**Issue by kagranger** [kagranger/petpeople#6]
**Task list**
- [x] Update the component hierarchy.
- [x] Break ViewListing component into two components--ViewListing and ListingCard.
- [x] Adjust post get route to find more than one listing.
- [x] Create a function to map through data array.
- [x] Adjust handleDelete function to account for multiple listings. 
- [x] Update wireframe.

**Component Hierarchy**
```javascript
<App>
      <CreateListing />
      <view-listings>
            <ViewListing>
                  <ListingCard>
                        <DeleteListing />
                  </ListingCard>
            </ViewListing>  
      <view-listings>
</App>
```
**Data Flow**

<img width="320" alt="screen shot 2018-05-25 at 5 28 45 pm" src="https://user-images.githubusercontent.com/36418379/40570580-1bbe5306-6041-11e8-941f-7ad4ec2d0965.png">

**Data Model**
```javascript
{
    listings : [
        {
            type: "",
            breed: "",
            image: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                city-state: "",
                website: ""
             }
        },
        {
            type: "",
            breed: "",
            image: "",
            availability: "",
            additional-info: "",
            contact: {
                name: "",
                phone: "",
                email: "",
                city-state: "",
                website: ""
             }
        },
        ...
    ]
}
```

**Wireframe**

<img width="721" alt="screen shot 2018-05-25 at 5 19 31 pm" src="https://user-images.githubusercontent.com/36418379/40570442-d82b700c-603f-11e8-9bbc-aff2e4a906f0.png">

<img width="1318" alt="screen shot 2018-05-25 at 5 26 24 pm" src="https://user-images.githubusercontent.com/36418379/40570546-cdb5d238-6040-11e8-8996-a694e6f60313.png">
